#!/USR/BIN/PYTHON3
"""DEFINES A BASE GEOMETRY CLASS BASEGEOMETRY."""


CLASS BASEGEOMETRY:
    """REPRSENT BASE GEOMETRY."""

    DEF AREA(SELF):
        """NOT YET IMPLEMENTED."""
        RAISE EXCEPTION("AREA() IS NOT IMPLEMENTED")

    DEF INTEGER_VALIDATOR(SELF, NAME, VALUE):
        """VALIDATE A PARAMETER AS AN INTEGER.

        ARGS:
            NAME (STR): THE NAME OF THE PARAMETER.
            VALUE (INT): THE PARAMETER TO VALIDATE.
        RAISES:
            TYPEERROR: IF VALUE IS NOT AN INTEGER.
            VALUEERROR: IF VALUE IS <= 0.
        """
        IF TYPE(VALUE) != INT:
            RAISE TYPEERROR("{} MUST BE AN INTEGER".FORMAT(NAME))
        IF VALUE <= 0:
            RAISE VALUEERROR("{} MUST BE GREATER THAN 0".FORMAT(NAME))
